name: Build & Push API Docker Image
on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "apps/api/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "turbo.json"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/fishi-api:latest
            ghcr.io/${{ github.repository_owner }}/fishi-api:${{ github.sha }}
